name: trendoapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amazon_cognito_identity_dart_2: ^1.0.3
  comment_box: ^0.0.16
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  dropdown_below: ^0.0.7
  email_validator: ^2.0.1
  expandable: ^5.0.1
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.6
  geocoding: ^2.0.0
  geolocator: ^7.0.0
  google_maps_flutter: ^2.0.6
  http: ^0.13.3
  image_picker: ^0.7.5+2
  intl: ^0.17.0
  # keyboard_avoider: ^0.1.2
  nearby_connections: ^3.1.0
  path_provider: ^2.0.2
  permission_handler: ^8.0.1
  pin_code_fields: ^7.1.0
  provider: ^5.0.0
  responsive_framework: ^0.1.2
  shared_preferences: ^2.0.6
  syncfusion_flutter_charts: ^19.1.69
  syncfusion_flutter_sliders: ^19.1.69-beta
  get_storage: ^2.0.2
  # custom_switch: ^0.0.1
  flutter_switch: ^0.3.2
  email_launcher: ^1.1.1
  url_launcher: ^6.0.9
  lottie: ^1.1.0
  cached_network_image: ^3.0.0
  scroll_to_index: ^2.0.0
  enum_to_string: ^2.0.1
  group_radio_button: ^1.1.0
  pull_to_refresh: ^2.0.0
  onesignal_flutter: ^3.2.7
  day_night_time_picker: ^1.0.5
  timezone: ^0.8.0
  flutter_typeahead: ^3.2.4
  autocomplete_textfield: ^2.0.1
  carousel_slider: ^4.1.1
  fbroadcast: ^2.0.0
  flutter_map: ^2.2.0
  intl_phone_number_input: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gifs/
    - assets/json/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BC Alphapipe
      fonts:
        - asset: assets/fonts/BC_Alphapipe_RB_Bold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
